apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
    name: ebs-storage-class
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
