apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: demo-voting-app
    name: result-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app
        app: demo-voting-app
    spec:
      containers:
      - name: result-app-pod
        image: kodekloud/examplevotingapp_result:v1
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
